# Generated by Django 5.1.5 on 2025-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendprofile',
            name='age',
            field=models.IntegerField(default=63),
        ),
        migrations.AddField(
            model_name='friendprofile',
            name='full_name',
            field=models.CharField(default='john mwangi', max_length=255),
        ),
        migrations.AddField(
            model_name='friendprofile',
            name='hometown',
            field=models.CharField(default='Makutano', max_length=255),
        ),
    ]
